name: oPool
channels:
  - bioconda
  - conda-forge
  - defaults
dependencies:
  - python=3.9
  - pip
  - pandas
  - numpy
  - openpyxl
  - biopython
  - abnumber
  - rich
  - cd-hit
  - hmmer
  - blast
  - pip:
    - Flask==2.3.3
    - Werkzeug==2.3.7
    - crowelab-pyir 